### ISSUE TITLE
Update the Readme for build.gradle

### ISSUE THREAD

**Issue by leenasn** [multunus/onemdm-installer#2]
Apart from importing, I think we also need to add the following line to build.gradle

`compile project(':onemdm_installer')`

Without the above, it didn't work for me.

@yedhukrishnan wondering whether how it worked for you without that. Can you check and make the appropriate changes? Thx.

**Comment by yedhukrishnan** [comment]
@leenasn Ya.. I missed that part. I'll add it now.
